### ISSUE TITLE
IE8 Parser Error - language_in needs to be set to ECMASCRIPT5

### ISSUE THREAD

**Issue by alex-barberi** [michaldudek/Bundy#2]
First off, let me say... Bundy is the greatest thing ever created.

Unfortunately, I get this error:
    ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting new versions of JS, set the appropriate language_in option.

I am getting that error because one of my JS files has lots of array lists with trailing commas, because that is allowed in EcmaScript5.

The solution is to run the Google Closure Compiler with --language_in=ECMASCRIPT, but I do not know how to change bundy to make it do that.

**Comment by alex-barberi** [comment]
Oh...Haha. Found it...

		new compressor.minify({
		    type: 'gcc',
		    language: 'ECMASCRIPT5',
			fileIn : src,
			fileOut : dest,
			callback : function(err) {
				if (err) {
					return utils.logError(err);
				}

				// get the compressed size
				var compressedSize = fs.statSync(dest).size;

				// report on what we achieved
				utils.log(thInfo('Compressed: ') + utils.bytesToString(compressedSize, 2) + ' (' + utils.formatNumber(compressedSize / totalFileSize * 100) + '%)');
				utils.log(thInfo('Saved:  ') + dest);
				utils.log();

				// and continue to the next job
				doNext();
			}
		});

**Comment by michaldudek** [comment]
Haha, thank you very much :)

I added your suggestion and tagged Bundy with version `0.1.2` so if you `npm update` you should get the fix.

I haven't used Bundy for years.. and didn't think anyone is using it ;) You'd probably be better off moving to Gulp or Webpack which are widely supported by the community and handle cases like this (and many other you wouldn't think of) already.

But anyway, thanks for this contribution :)

**Comment by ghost** [comment]
You are a gentleman and a scholar.

I have been using Bundy for a long time and I love it. I do not want to give it up. It's so simple!
